language: node_js
node_js:
  - "node"
before_script:
  - cd video-url-parser && npm install --save-dev mocha && npm install --save-dev chai && npm install --save-dev webpack 
script:
  - npm run test
